### ISSUE TITLE
Some error occured 

### ISSUE THREAD

**Issue by aoshimak** [xndcn/pebble-firmware-utils#5]
For my environment under python2.7, I cannot use xndcn's utilities with Pebble SDK 3.0beta or 3.0 with some errors. So I use SDK 2.9 and rewrite the path on xndcn's pbpack_tool.py for its directory structure of SDK2.9's.
(I use only monochrome model, so it is easy way to make language packs.)

Error messages (when I use pbpack_tool.py with SDK3.0) :

> python pbpack_tool.py unpack ..\pbl\IdlEZEQ-zh_CN_15.pbl .
> Traceback (most recent call last):
>   File "pbpack_tool.py", line 61, in <module>
>     main()
>   File "pbpack_tool.py", line 58, in main
>     args.func(args)
>   File "pbpack_tool.py", line 23, in cmd_unpack
>     pack = ResourcePack.deserialize(pack_file)
>   File "e:\pebble\PebbleSDK-3.0\Pebble/common/tools\pbpack.py", line 77, in dese
> rialize
>     resource_pack = cls()
> TypeError: **init**() takes exactly 2 arguments (1 given)

Thanks in advance.

**Comment by xndcn** [comment]
@aoshimak Sorry for that. It seems a bug in SDK3.0, I will try to fix it later, thank you!

**Comment by xndcn** [comment]
@aoshimak I have to fix this bug by myself, please use the new version `pbpack_tool.py` and check it again, thanks!

**Comment by xndcn** [comment]
2929c09dbb13a66f30eff9062a5b0638772c3620

**Comment by funkycode** [comment]
I think that the bug was fixed in 3.4
I get the following error:

lang/pbpack_tool.py unpack cyr1.pbl cyrrilic
Traceback (most recent call last):
  File "lang/pbpack_tool.py", line 73, in <module>
    main()
  File "lang/pbpack_tool.py", line 69, in main
    args.func(args)
  File "lang/pbpack_tool.py", line 34, in cmd_unpack
    pack = ResourcePack.deserialize(pack_file)
  File "/home/zogg/pebble/PebbleSDK-3.4/Pebble/common/tools/pbpack.py", line 81, in deserialize
    resource_pack = cls(is_system)
TypeError: hacked_init() takes exactly 1 argument (2 given)

If i comment out #fix_ResourcePack_bug() in your code it fixes the issue (though i get other error related to crc calculation but i think i'll open it as different issue)

**Comment by xndcn** [comment]
@funkycode Thank you very much! Now fixed, please update and try it again.
